name: Generate Datas

on:
  schedule: # executar a cada 12 horas
    - cron: "* */12 * * *"
  workflow_dispatch:
  
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # animação da cobra
      - uses: Platane/snk@master
      id: snake-gif
      with:
        github_user_name: Gilberto-Martins
        svg_out_path: dist/github-contribution-grid-snake.svg
        
      - uses: craz-mas/ghaction-github-pages@v2.1.3
      with:
        y=target_branch: ouptup
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
